import email.utils
import hashlib
import html
import os
import re
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FEED_PATH = ROOT / "docs" / "feed.xml"

MAX_ITEMS = int(os.environ.get("RSS_MAX_ITEMS", "100"))


def default_site_url() -> str:
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    if "/" not in repo:
        return "https://example.com"

    owner, name = repo.split("/", 1)
    return f"https://{owner}.github.io/{name}"


SITE_URL = os.environ.get("RSS_SITE_URL", "").rstrip("/") or default_site_url()
FEED_URL = f"{SITE_URL}/feed.xml"


def now_rfc2822() -> str:
    return email.utils.format_datetime(datetime.now(timezone.utc))


def extract_title(report: str) -> str:
    for line in report.splitlines():
        stripped = line.strip()
        if not stripped:
            continue

        match = re.search(r"^(CHANGED|NEW|ERROR):\s*(.+)$", stripped, re.IGNORECASE)
        if match:
            return match.group(2)[:120]

    return "urlwatch detected changes"


def item_guid(report: str, timestamp: str) -> str:
    digest = hashlib.sha256((timestamp + "\n" + report).encode("utf-8")).hexdigest()
    return f"urlwatch:{digest}"


def ensure_feed() -> ET.ElementTree:
    if FEED_PATH.exists() and FEED_PATH.read_text(encoding="utf-8").strip():
        tree = ET.parse(FEED_PATH)
        channel = get_channel(tree)
        set_or_create(channel, "title", "urlwatch updates")
        set_or_create(channel, "link", SITE_URL)
        set_or_create(channel, "description", "Change notifications generated by urlwatch")
        set_or_create(channel, "language", "ja")
        return tree

    rss = ET.Element("rss", {"version": "2.0"})
    channel = ET.SubElement(rss, "channel")

    ET.SubElement(channel, "title").text = "urlwatch updates"
    ET.SubElement(channel, "link").text = SITE_URL
    ET.SubElement(channel, "description").text = "Change notifications generated by urlwatch"
    ET.SubElement(channel, "language").text = "ja"
    ET.SubElement(channel, "lastBuildDate").text = now_rfc2822()

    return ET.ElementTree(rss)


def get_channel(tree: ET.ElementTree) -> ET.Element:
    root = tree.getroot()
    channel = root.find("channel")
    if channel is None:
        raise RuntimeError("Invalid RSS feed: channel not found")
    return channel


def set_or_create(parent: ET.Element, tag: str, text: str) -> None:
    child = parent.find(tag)
    if child is None:
        child = ET.SubElement(parent, tag)
    child.text = text


def append_item(report: str) -> None:
    timestamp = now_rfc2822()
    title = extract_title(report)

    tree = ensure_feed()
    channel = get_channel(tree)

    set_or_create(channel, "link", SITE_URL)
    set_or_create(channel, "lastBuildDate", timestamp)

    item = ET.Element("item")
    ET.SubElement(item, "title").text = title
    ET.SubElement(item, "link").text = FEED_URL
    ET.SubElement(item, "guid", {"isPermaLink": "false"}).text = item_guid(report, timestamp)
    ET.SubElement(item, "pubDate").text = timestamp

    escaped_report = html.escape(report)
    ET.SubElement(item, "description").text = f"<pre>{escaped_report}</pre>"

    first_item_index = None
    children = list(channel)
    for index, child in enumerate(children):
        if child.tag == "item":
            first_item_index = index
            break

    if first_item_index is None:
        channel.append(item)
    else:
        channel.insert(first_item_index, item)

    items = channel.findall("item")
    for old_item in items[MAX_ITEMS:]:
        channel.remove(old_item)

    FEED_PATH.parent.mkdir(parents=True, exist_ok=True)
    ET.indent(tree, space="  ")
    tree.write(FEED_PATH, encoding="utf-8", xml_declaration=True)


def main() -> None:
    report = sys.stdin.read().strip()
    if not report:
        return
    append_item(report)


if __name__ == "__main__":
    main()
